# Generated by Django 6.0.4 on 2026-08-10 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
        ('surveys', '0002_alter_choice_options_alter_module_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'respuesta', 'verbose_name_plural': 'respuestas'},
        ),
        migrations.AlterModelOptions(
            name='surveysubmission',
            options={'ordering': ['-started_at'], 'verbose_name': 'envío de encuesta', 'verbose_name_plural': 'envíos de encuesta'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question', verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.surveysubmission', verbose_name='envío'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.JSONField(help_text='Valor de la respuesta; su interpretación depende del tipo de pregunta.', verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='surveys.surveyassignment', verbose_name='asignación'),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de término'),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completado')], default='in_progress', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='colaborador'),
        ),
    ]
