# Generated by Django 6.0.4 on 2026-08-05 00:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.CreateModel(
            name='CompanyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Como debe aparecer en la lista que ve el colaborador.', max_length=120, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca para retirarla de la lista sin borrarla. Los colaboradores ya asignados la conservan.', verbose_name='activa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accounts.company')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.companyarea', verbose_name='área'),
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Como debe aparecer en la lista que ve el colaborador.', max_length=120, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca para retirarla de la lista sin borrarla. Los colaboradores ya asignados la conservan.', verbose_name='activa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.company')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.companylocation', verbose_name='localidad'),
        ),
        migrations.AddConstraint(
            model_name='companyarea',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), name='accounts_companyarea_unique_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companylocation',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), name='accounts_companylocation_unique_name_per_company'),
        ),
    ]
