# Generated by Django 6.0.4 on 2026-04-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_manage_site_configuration", "Can manage site configuration"),
                    ("can_manage_users", "Can manage users"),
                    ("can_manage_surveys", "Can manage surveys"),
                    ("can_assign_surveys", "Can assign surveys"),
                    ("can_view_dashboard", "Can view dashboard"),
                    ("can_view_reports", "Can view reports"),
                    ("can_view_insights", "Can view insights"),
                    ("can_take_assigned_surveys", "Can take assigned surveys"),
                ],
                "managed": False,
            },
        ),
    ]
