# Generated by Django 6.0.4 on 2026-08-10 01:44

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_department_companyarea_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyarea',
            name='accounts_companyarea_unique_name_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='companylocation',
            name='accounts_companylocation_unique_name_per_company',
        ),
        migrations.AddConstraint(
            model_name='companyarea',
            constraint=models.UniqueConstraint(models.F('company'), apps.accounts.models.FoldCatalogName('name'), name='accounts_companyarea_unique_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companylocation',
            constraint=models.UniqueConstraint(models.F('company'), apps.accounts.models.FoldCatalogName('name'), name='accounts_companylocation_unique_name_per_company'),
        ),
    ]
