# Generated by Django 6.0.4 on 2026-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='expected_employee_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
