# Generated by Django 6.0.4 on 2026-08-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_companyarea_accounts_companyarea_unique_name_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(db_collation='es-MX-x-icu', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_collation='es-MX-x-icu', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyarea',
            name='name',
            field=models.CharField(db_collation='es-MX-x-icu', help_text='Como debe aparecer en la lista que ve el colaborador.', max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='name',
            field=models.CharField(db_collation='es-MX-x-icu', help_text='Como debe aparecer en la lista que ve el colaborador.', max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_collation='es-MX-x-icu', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_collation='es-MX-x-icu', max_length=150, verbose_name='last name'),
        ),
    ]
