# Generated by Django 6.0.4 on 2026-08-10 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_legal_name_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='emailotp',
            options={'verbose_name': 'código OTP', 'verbose_name_plural': 'códigos OTP'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False, 'permissions': [('can_manage_surveys', 'Puede administrar encuestas'), ('can_view_dashboard', 'Puede ver el tablero'), ('can_view_insights', 'Puede ver la valoración de resultados'), ('can_take_assigned_surveys', 'Puede contestar las encuestas asignadas'), ('can_manage_employees', 'Puede administrar empleados'), ('can_view_submissions', 'Puede ver los envíos')], 'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='setupaccesscode',
            options={'verbose_name': 'código temporal de acceso', 'verbose_name_plural': 'códigos temporales de acceso'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'perfil de colaborador', 'verbose_name_plural': 'perfiles de colaborador'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='domicilio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(db_collation='es-MX-x-icu', max_length=255, verbose_name='razón social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_collation='es-MX-x-icu', max_length=255, verbose_name='nombre comercial'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Se genera solo. El colaborador lo captura al activar su cuenta.', max_length=5, unique=True, verbose_name='código de referencia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='companyarea',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accounts.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=6, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(verbose_name='expira el'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='usado'),
        ),
        migrations.AlterField(
            model_name='setupaccesscode',
            name='code',
            field=models.CharField(blank=True, help_text='Se borra en cuanto se usa.', max_length=9, null=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='setupaccesscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='setupaccesscode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de uso'),
        ),
        migrations.AlterField(
            model_name='setupaccesscode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_access_codes', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_collation='es-MX-x-icu', max_length=150, verbose_name='nombre(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_collation='es-MX-x-icu', max_length=150, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Obliga a definir una contraseña nueva en el siguiente ingreso.', verbose_name='debe cambiar su contraseña'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Se marca sola cuando el colaborador completa su activación.', verbose_name='cuenta activada'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
