# Generated by Django 6.0.4 on 2026-05-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_expected_employee_count_add_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='rfc',
            field=models.CharField('RFC', blank=True, max_length=13),
        ),
    ]
