# Generated by Django 6.0.4 on 2026-08-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_options_alter_emailotp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False, 'permissions': [('can_manage_surveys', 'Puede administrar encuestas'), ('can_view_dashboard', 'Puede ver el tablero'), ('can_view_insights', 'Puede ver la valoración de resultados'), ('can_take_assigned_surveys', 'Puede contestar las encuestas asignadas'), ('can_manage_employees', 'Puede administrar colaboradores'), ('can_view_submissions', 'Puede ver los envíos')], 'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
    ]
