# Generated by Django 6.0.4 on 2026-08-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_role_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='maternal_last_name',
            field=models.CharField(blank=True, db_collation='es-MX-x-icu', max_length=150, verbose_name='apellido materno'),
        ),
        migrations.AddField(
            model_name='user',
            name='paternal_last_name',
            field=models.CharField(blank=True, db_collation='es-MX-x-icu', max_length=150, verbose_name='apellido paterno'),
        ),
    ]
