# Generated by Django 6.0.4 on 2026-06-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupAccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=9, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_access_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="setupaccesscode",
            constraint=models.UniqueConstraint(
                condition=Q(("code__isnull", False)),
                fields=("code",),
                name="unique_active_setup_access_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="setupaccesscode",
            constraint=models.UniqueConstraint(
                condition=Q(("used_at__isnull", True)),
                fields=("user",),
                name="unique_unused_setup_access_code_per_user",
            ),
        ),
    ]
