# Generated by Django 6.0.4 on 2026-07-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_setupaccesscode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
