# Generated by Django 6.0.4 on 2026-08-24 04:38

from django.db import migrations, models


def deactivate_profiles(apps, schema_editor):
    """Send every employee back through activation.

    Sexo and fecha de nacimiento can only come from the employee, so there is
    nothing to backfill from.
    """
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.update(is_activated=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_last_name_user_maternal_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=6, verbose_name='sexo'),
        ),
        migrations.RunPython(deactivate_profiles, migrations.RunPython.noop),
    ]
