# Generated by Django 6.0.4 on 2026-09-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_date_of_birth_userprofile_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False, 'permissions': [('can_manage_surveys', 'Puede administrar encuestas'), ('can_view_dashboard', 'Puede ver el tablero'), ('can_view_insights', 'Puede ver la valoración de resultados'), ('can_take_assigned_surveys', 'Puede contestar las encuestas asignadas'), ('can_manage_employees', 'Puede administrar colaboradores'), ('can_view_submissions', 'Puede ver los envíos'), ('can_view_small_groups', 'Puede ver resultados de grupos pequeños')], 'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
    ]
