# Generated by Django 6.0.4 on 2026-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_role_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, verbose_name='actividad principal'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_center',
            field=models.CharField(blank=True, max_length=255, verbose_name='centro de trabajo'),
        ),
    ]
