# Generated by Django 6.0.4 on 2026-06-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(default=0)),
                ('final_ndr', models.CharField(choices=[('nulo', 'Nulo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], default='nulo', max_length=10)),
                ('guia1_event', models.BooleanField(default=False)),
                ('guia1_followup_count', models.IntegerField(default=0)),
                ('guia1_severity', models.CharField(choices=[('none', 'Ninguna'), ('low', 'Baja'), ('med', 'Media'), ('high', 'Alta')], default='none', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nom035_score', to='responses.surveysubmission')),
            ],
        ),
        migrations.CreateModel(
            name='GroupScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('categoria', 'Categoría'), ('dominio', 'Dominio'), ('dimension', 'Dimensión')], max_length=12)),
                ('key', models.CharField(max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('ndr', models.CharField(choices=[('nulo', 'Nulo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], default='nulo', max_length=10)),
                ('submission_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='nom035.submissionscore')),
            ],
            options={
                'indexes': [models.Index(fields=['submission_score', 'level'], name='nom035_grou_submiss_008988_idx'), models.Index(fields=['level', 'ndr'], name='nom035_grou_level_17a831_idx')],
                'unique_together': {('submission_score', 'level', 'key')},
            },
        ),
    ]
