# Generated by Django 6.0.4 on 2026-06-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom035', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupscore',
            name='level',
            field=models.CharField(choices=[('categoria', 'Categoría'), ('dominio', 'Dominio')], max_length=12),
        ),
    ]
