# Generated by Django 6.0.4 on 2026-08-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom035', '0001_initial'),
        ('responses', '0002_alter_answer_options_alter_surveysubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupscore',
            options={'verbose_name': 'puntaje por grupo', 'verbose_name_plural': 'puntajes por grupo'},
        ),
        migrations.AlterModelOptions(
            name='submissionscore',
            options={'verbose_name': 'valoración', 'verbose_name_plural': 'valoraciones'},
        ),
        migrations.AlterField(
            model_name='groupscore',
            name='key',
            field=models.CharField(max_length=64, verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='groupscore',
            name='level',
            field=models.CharField(choices=[('categoria', 'Categoría'), ('dominio', 'Dominio'), ('dimension', 'Dimensión')], max_length=12, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='groupscore',
            name='ndr',
            field=models.CharField(blank=True, choices=[('nulo', 'Nulo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], default='nulo', max_length=10, verbose_name='nivel de riesgo'),
        ),
        migrations.AlterField(
            model_name='groupscore',
            name='score',
            field=models.IntegerField(default=0, verbose_name='puntaje'),
        ),
        migrations.AlterField(
            model_name='groupscore',
            name='submission_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='nom035.submissionscore', verbose_name='valoración'),
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='computed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de cálculo'),
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='final_ndr',
            field=models.CharField(choices=[('nulo', 'Nulo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], default='nulo', max_length=10, verbose_name='nivel de riesgo final'),
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='final_score',
            field=models.IntegerField(default=0, verbose_name='puntaje final'),
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='guia1_positive',
            field=models.BooleanField(default=False, verbose_name='positivo en Guía I'),
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nom035_score', to='responses.surveysubmission', verbose_name='envío'),
        ),
    ]
