# Generated by Django 6.0.4 on 2026-09-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom035', '0002_alter_groupscore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionscore',
            name='guia1_event',
            field=models.BooleanField(default=False, verbose_name='acontecimiento traumático severo'),
        ),
    ]
