# Generated by Django 6.0.4 on 2026-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom035', '0002_alter_groupscore_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionscore',
            name='guia1_event',
        ),
        migrations.RemoveField(
            model_name='submissionscore',
            name='guia1_followup_count',
        ),
        migrations.RemoveField(
            model_name='submissionscore',
            name='guia1_severity',
        ),
        migrations.AddField(
            model_name='submissionscore',
            name='guia1_positive',
            field=models.BooleanField(default=False),
        ),
    ]
