# Generated by Django 6.0.4 on 2026-07-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nom035", "0003_remove_submissionscore_guia1_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupscore",
            name="level",
            field=models.CharField(
                choices=[
                    ("categoria", "Categoría"),
                    ("dominio", "Dominio"),
                    ("dimension", "Dimensión"),
                ],
                max_length=12,
            ),
        ),
    ]
