# Generated by Django 6.0.4 on 2026-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nom035", "0004_alter_groupscore_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupscore",
            name="ndr",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nulo", "Nulo"),
                    ("bajo", "Bajo"),
                    ("medio", "Medio"),
                    ("alto", "Alto"),
                    ("muy_alto", "Muy alto"),
                ],
                default="nulo",
                max_length=10,
            ),
        ),
    ]
