# Generated by Django 6.0.4 on 2026-08-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_options_alter_emailotp_options_and_more'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order'], 'verbose_name': 'opción', 'verbose_name_plural': 'opciones'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'módulo', 'verbose_name_plural': 'módulos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'pregunta', 'verbose_name_plural': 'preguntas'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'encuesta', 'verbose_name_plural': 'encuestas'},
        ),
        migrations.AlterModelOptions(
            name='surveyassignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'asignación de encuesta', 'verbose_name_plural': 'asignaciones de encuesta'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.CharField(max_length=255, verbose_name='etiqueta'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question', verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=255, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='module',
            name='applies_to',
            field=models.CharField(choices=[('all', 'Todos los participantes'), ('small', 'Variante pequeña'), ('large', 'Variante grande')], default='all', max_length=10, verbose_name='aplica a'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='Párrafo opcional. Se muestra como subtítulo bajo el título, o por sí solo cuando el título está vacío.', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='module',
            name='intro',
            field=models.TextField(blank=True, help_text='Encabezado opcional arriba del título o divisor, para el texto introductorio de una guía (p. ej. el nombre formal del cuestionario).', verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='module',
            name='key',
            field=models.SlugField(help_text='Identificador estable, único dentro de la encuesta. Lo referencian las reglas de visible_when (any_in_module).', max_length=64, verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='module',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='surveys.survey', verbose_name='encuesta'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, help_text='Encabezado divisor opcional, arriba de las preguntas del módulo. Déjalo vacío si el módulo solo presenta texto (ver descripción).', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='module',
            name='visible_when',
            field=models.JSONField(blank=True, help_text='Regla opcional de visibilidad condicional. Vacío = siempre visible.', null=True, verbose_name='condición de visibilidad'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.SlugField(help_text="Identificador estable dentro de la encuesta, p. ej. 'g3-29'. Es la llave de integración que consume el motor de valoración.", max_length=64, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='question',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración flexible por tipo: min, max, placeholder, labels, etc.', verbose_name='configuración'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.module', verbose_name='módulo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto'), ('integer', 'Número entero'), ('decimal', 'Número decimal'), ('date', 'Fecha'), ('single_choice', 'Opción única'), ('multiple_choice', 'Opción múltiple'), ('boolean', 'Sí / No'), ('rating', 'Calificación'), ('likert', 'Escala Likert')], max_length=20, verbose_name='tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='encuesta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='visible_when',
            field=models.JSONField(blank=True, help_text='Regla opcional de visibilidad condicional. Vacío = siempre visible.', null=True, verbose_name='condición de visibilidad'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='headcount_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Las empresas con más colaboradores que este número reciben la variante grande; las demás, la pequeña.', verbose_name='umbral de plantilla'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='key',
            field=models.SlugField(help_text="Identificador estable del instrumento, p. ej. 'nom035'.", max_length=64, unique=True, verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('archived', 'Archivada')], default='draft', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='accounts.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha límite'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada')], default='active', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveys.survey', verbose_name='encuesta'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='variant',
            field=models.CharField(choices=[('small', 'Guía II'), ('large', 'Guía III')], help_text='Se fija al crear la asignación; no cambia si cambia la plantilla.', max_length=10, verbose_name='variante'),
        ),
    ]
