# Generated by Django 6.0.4 on 2026-07-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='variant',
            field=models.CharField(choices=[('small', 'Guía II'), ('large', 'Guía III')], help_text='Frozen at creation; does not change if headcount changes.', max_length=10),
        ),
    ]
