# Generated by Django 6.0.4 on 2026-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_required_from_question_and_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('boolean', 'Boolean'), ('rating', 'Rating'), ('likert', 'Likert Scale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('boolean', 'Boolean'), ('rating', 'Rating'), ('likert', 'Likert Scale')], max_length=20),
        ),
    ]
