# Generated by Django 6.0.4 on 2026-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_surveyassignment_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='intro',
            field=models.TextField(blank=True, help_text="Optional heading shown above the module's title/divider, for guide-level intro text (e.g. a questionnaire's formal name)."),
        ),
    ]
