# Generated by Django 6.0.4 on 2026-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_module_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='Optional paragraph text. Shown under the title as a subtitle when title is set, or standalone when title is blank.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, help_text="Optional divider heading shown above the module's questions. Leave blank for a module presented as plain paragraph text only (see description).", max_length=255),
        ),
    ]
