# Generated by Django 6.0.4 on 2026-10-05 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0002_alter_choice_options_alter_module_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='estado')),
                ('snapshot', models.JSONField(blank=True, null=True, verbose_name='datos publicados')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('issued_in', models.CharField(blank=True, max_length=120, verbose_name='lugar de emisión')),
                ('activities_summary', models.TextField(blank=True, verbose_name='principales actividades')),
                ('headcount_in_person', models.PositiveIntegerField(blank=True, null=True, verbose_name='personal presencial')),
                ('headcount_home_office', models.PositiveIntegerField(blank=True, null=True, verbose_name='personal en home office')),
                ('headcount_hybrid', models.PositiveIntegerField(blank=True, null=True, verbose_name='personal híbrido')),
                ('evaluator_name', models.CharField(blank=True, max_length=200, verbose_name='responsable de la evaluación')),
                ('evaluator_license', models.CharField(blank=True, max_length=40, verbose_name='cédula profesional')),
                ('additional_recommendations', models.TextField(blank=True, verbose_name='recomendaciones adicionales')),
                ('conclusions', models.TextField(blank=True, verbose_name='conclusiones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='surveys.surveyassignment', verbose_name='asignación')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='ReportSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='cargo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='reports.report', verbose_name='reporte')),
            ],
            options={
                'verbose_name': 'responsable de la empresa',
                'verbose_name_plural': 'responsables de la empresa',
                'ordering': ('order', 'pk'),
            },
        ),
    ]
